# Generated by Django 4.0.3 on 2022-03-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_user_id_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='NULL', upload_to='profile_pics'),
        ),
    ]
