# Generated by Django 4.0.3 on 2022-03-18 22:26

from django.db import migrations, models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(upload_to=signup.models.profile_pic_path, verbose_name='Profile Pic'),
        ),
    ]
