# Generated by Django 4.0.3 on 2022-03-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0008_remove_user_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(upload_to='profile_pic')),
                ('phone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='signup.user')),
            ],
        ),
    ]
