# Generated by Django 4.0.3 on 2022-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_profilepic_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='phone',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
